version: '3.8'
services:

#  traefik:
#    image: 'traefik:2.3'
#    restart: 'always'
#    ports:
#      - '443:443'
#      - '80:80'
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock:ro'
#      - /letsencrypt:/letsencrypt
#    command:
#      - '--api=false'
#      - '--api.dashboard=false'
#      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
#      - '--providers.docker.exposedbydefault=false'
#      - '--providers.docker.network=traefik-public'
#      - '--entrypoints.web.address=:80'
#      - '--entrypoints.websecure.address=:443'
#      - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true'
#      - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web'
#      - '--certificatesresolvers.letsencryptresolver.acme.email=mark.basham@rfi.ac.uk'
#      - '--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json'
#    labels:
#      - 'traefik.enable=true'
#      # HTTP Catchall for redirecting HTTP -> HTTPS
#      - 'traefik.http.routers.http-catchall.rule=PathPrefix(`/`)'
#      - 'traefik.http.routers.http-catchall.entrypoints=web'
#      - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
#      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'

  webserver:
    restart: always
    image: rosalindfranklininstitute/wellspring2xlsx:latest
    ports:
      - "5000:5000"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.nginx.rule=(Host(`wellspring2xlsx.rfi.ac.uk`))'
      - 'traefik.http.routers.nginx.entrypoints=websecure'
      - 'traefik.http.routers.nginx.tls.certresolver=letsencryptresolver'
      - 'traefik.http.routers.nginx.service=nginxservice'
      - 'traefik.http.services.nginxservice.loadbalancer.server.port=80'
    depends_on:
      - traefik
