name: CI - Build Container Images and Push to Dockerhub

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build_env:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
      # Configure environment variable depending on which branch we are running on
      - name: Set env to master
        if: endsWith(github.ref, '/main')
        run: echo "DOCKER_REPO_TAG=wellspring2xlsx:latest" >> $GITHUB_ENV
      - name: Set env to branch
        if: (!endsWith(github.ref, '/main'))
        run: echo "DOCKER_REPO_TAG=wellspring2xlsx:${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Set image name
        run: echo "DOCKER_REPO_NAME=${{ secrets.DOCKER_ORG }}/$DOCKER_REPO_TAG" >> $GITHUB_ENV

      # Checks-out repository under $(pwd)
      - uses: actions/checkout@v2

      # Build Docker image, push image to Dockerhub on success
      - name: Pull existing Docker image
        run: docker pull $DOCKER_REPO_NAME || true

      - name: Build Docker image
        run: |
          docker build --pull --cache-from $DOCKER_REPO_NAME --tag $DOCKER_REPO_NAME -f Dockerfile .

      - name: Push Docker image to Dockerhub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push $DOCKER_REPO_NAME
        if: (!startsWith(github.ref, 'refs/pull/'))
